name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy to EC2
        run: |
          ssh -i ${{ secrets.EC2_SSH_KEY }} ubuntu@ec2-13-49-77-23.eu-north-1.compute.amazonaws.com 'cd /path/to/olive && git pull origin main && npm install && npm run restart'
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
